# Generated by Django 3.0.7 on 2020-06-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200613_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='overview',
            new_name='after_header',
        ),
        migrations.AddField(
            model_name='post',
            name='all_text',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='header',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='quote',
            field=models.TextField(default=True),
            preserve_default=False,
        ),
    ]
